export const API_KEY="930feb26349f59ff3f30771a7cc997c6"
export const API_IMG="https://image.tmdb.org/t/p/original/"
export const API_GENRE="https://api.themoviedb.org/3/genre/movie/list"
export const API_MOVIE_LIST="https://api.themoviedb.org/3/discover/movie"
export const API_MOVIE_DETAIL="https://api.themoviedb.org/3/movie"